id: I9AEE9A28
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:52:37.576034'
last_modified: '2022-06-19T09:52:37.576047'
parser: null
source_metadata:
  title: Hagiography of sDings ma ba bsLabs gsum rgyal mtshan (1526–1577); Lamdre
    Lobshe, vol. nga, title no. 2
  author: ཞྭ་ལུ་མཁན་ཆེན་དབང་ཕྱུག་རབ་བརྟན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-03);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/568
  bases:
    8c53:
      title: Hagiography of sDings ma ba bsLabs gsum rgyal mtshan (1526–1577); Lamdre
        Lobshe, vol. nga, title no. 2
      order: 1
      base_file: 8c53.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
